######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 22:12:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += copydlg.h copyjob.h mainwnd.h
FORMS += copydialog.ui mainwnd.ui
SOURCES += copydlg.cpp copyjob.cpp main.cpp mainwnd.cpp
